Repository UKHomeOffice/hocs-frontend, pull requests merged in 2022-05, with the labels that each got.

#961 HOCS-4802: change COMP_CCT_ENQ_REASON to dynamic
  server/lists/index.js
Labels: minor

#960 HOCS-4952: update BF regions and business areas
  server/lists/index.js
Labels: minor

#965 HOCS-5030: fix unauth error on SMC remove suspend
  server/services/action.js
Labels: patch

#970 HOCS-2083: change usage of Panel
  server/services/action.js
  src/shared/common/forms/__tests__/__snapshots__/panel.spec.js.snap
  src/shared/common/forms/panel.jsx
  src/shared/pages/form-enabled.jsx
Labels: patch

#971 HOCS-4547: remove GA implementation
  kube/kd/deployment.yaml
  package-lock.json
  package.json
  server/middleware/analytics.js
  server/routes/index.js
  src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap
  src/shared/common/components/__tests__/case-note.spec.jsx
  src/shared/common/components/__tests__/side-bar.spec.jsx
  src/shared/common/components/__tests__/workstack.spec.jsx
  src/shared/common/components/case-note.jsx
  src/shared/common/components/case-notes.jsx
  src/shared/common/components/side-bar.jsx
  src/shared/common/components/workstack.jsx
  src/shared/contexts/application.jsx
  src/shared/layouts/components/__tests__/__snapshots__/session-timer.spec.js.snap
  src/shared/layouts/page-enabled.jsx
  src/shared/pages/__tests__/__snapshots__/snapshot.spec.jsx.snap
  src/shared/pages/__tests__/__snapshots__/workstack.spec.jsx.snap
  src/shared/pages/__tests__/snapshot.spec.jsx
  src/shared/pages/__tests__/workstack.spec.jsx
  src/shared/pages/dashboard.jsx
  src/shared/pages/form-enabled.jsx
  src/shared/pages/search.jsx
  src/shared/pages/standardLines/standardLinesView.jsx
  src/shared/pages/workstack.jsx
Labels: minor

#962 HOCS-4951: offline transfer notes and flow fix
  server/lists/adapters/case-notes.js
Labels: minor

#959 HOCS-4409: Render tabs from DB
  server/lists/index.js
  server/middleware/__tests__/case.spec.js
  server/middleware/case.js
  server/routes/api/case.js
  src/shared/common/components/__tests__/__snapshots__/side-bar.spec.jsx.snap
  src/shared/common/components/__tests__/side-bar.spec.jsx
  src/shared/common/components/side-bar.jsx
  src/shared/contexts/actions/index.jsx
  src/shared/contexts/actions/types.jsx
  src/shared/contexts/application.jsx
  src/shared/helpers/__tests__/case-config-helpers.spec.js
  src/shared/helpers/api-status.js
  src/shared/helpers/case-config-helpers.js
  src/shared/helpers/case-type-sidebar-tabs-flags.js
  src/shared/pages/form-enabled.jsx
Labels: minor

#972 Feature/hocs 4800 ukvi complaints business area m UI
  package-lock.json
  server/lists/index.js
Labels: minor

#975 HOCS-5026: integrate ex-gratia into triage BF&BF2
  src/shared/common/components/__tests__/__snapshots__/tab-ex-gratia.spec.js.snap
  src/shared/common/components/__tests__/tab-ex-gratia.spec.js
  src/shared/common/components/tab-ex-gratia.jsx
Labels: minor

#978 HOCS-5088: Add search for SMC
  server/middleware/searchHandler.js
Labels: minor

#979 HOCS-4929 add SMC Complaint Origin list retrieval
  server/lists/index.js
Labels: minor

#981 HOCS-5140: Add G-Action Slack failure notification
  .github/workflows/semver.yml
Labels: skip-release

#964 HOCS-5036: retire unused bf business area list
  server/lists/index.js
Labels: patch
