Repository UKHomeOffice/hocs-frontend, pull requests merged in 2022-10, with the labels that each got.

#1127 HOCS-5679: refactor case creation document tag
  server/config/case-type/__tests__/case-type.spec.js
  server/config/case-type/case-type.js
  server/config/case-type/creation-document-tag.json
  server/services/__tests__/action.spec.js
  server/services/action.js
Labels: minor

#1129 Use en dash instead of hyphen-minus in test banner
  src/shared/common/components/__tests__/__snapshots__/phase-banner.spec.js.snap
  src/shared/common/components/phase-banner.jsx
Labels: patch

#1126 HOCS-5536: Enable visibilityConditions on mapped fields
  server/lists/adapters/case-view-unallocated.js
Labels: minor

#1130 HOCS-5632: IEDET - Complaint sub categories are not displayed correctly in Case Details accordion
  src/shared/common/forms/mapped-display.jsx
Labels: patch

#1138 HOCS-5693 Add missing initial document tag
  server/config/case-type/creation-document-tag.json
Labels: patch

#1132 HOCS-5684: Add get case for team endpoint
  server/lists/index.js
Labels: minor

#1141 HOCS-5561: Remove reference to missing file
  Dockerfile
Labels: patch

#1142 HOCS-5561: Correct chart name in drone
  .drone.yml
Labels: patch

#1143 HOCS-5561: Correct allow list quotes
  .drone.yml
Labels: patch

#1144 HOCS-5708/9: Fix tenant env value
  helm/hocs-frontend/templates/_envs.tpl
Labels: patch

#1145 HOCS-5561: Fix double dollar substitution bug
  .drone.yml
Labels: patch

#1146 HOCS-5561: Fix double dollar substitution bug
  .drone.yml
Labels: patch

#1147 HOCS-5561: Fix double dollar substitution bug
  .drone.yml
Labels: patch

#1148 HOCS-5561: Fix double dollar substitution bug
  .drone.yml
Labels: patch

#1153 HOCS-5652 - Add new POGR HMPO contribution business area list
  server/lists/index.js
Labels: minor

#1159 HOCS-5561: Bump chart to fix IP allowlist
  helm/hocs-frontend/Chart.yaml
Labels: patch

#1152 HOCS-5606: Ability to search by Application Reference
  server/config/searchFields/config.json
  server/middleware/searchHandler.js
Labels: minor

#1167 HOCS-5645: sentence-case unalloc accordion title
  server/lists/adapters/__tests__/__snapshots__/case-view-unallocated.spec.js.snap
  server/lists/adapters/case-view-unallocated.js
Labels: patch

#1166 HOCS-5638: sentence case form title
  server/services/forms/schemas/case-create.js
  server/services/forms/schemas/document-add.js
Labels: patch

#1164 HOCS-5544: Change PSU ref font size
  src/shared/common/forms/text.jsx
Labels: minor

#1168 HOCS-5647: Content changes - Record correspondent details screen
  server/services/forms/schemas/add-correspondent-details.js
  server/services/forms/schemas/update-correspondent-details.js
Labels: patch

#1169 HOCS-5840: change to search field label
  server/config/searchFields/config.json
Labels: patch

#1171 Chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies, patch

#1173 HOCS-5312: Create TO UKVI workstack
  server/lists/adapters/workstacks.js
  server/lists/index.js
Labels: minor

#1172 HOCS-5537: Add labelClassName to define new medium font size in Radio…
  src/shared/common/forms/radio-group.jsx
Labels: minor
