Repository UKHomeOffice/hocs-frontend, pull requests merged in 2022-07, with the labels that each got.

#1023 HOCS-5335: disable auto allocate
  server/config/tenant/config.json
Labels: patch

#1026 Bump NodeJS version
  Dockerfile
Labels: dependencies, patch

#1034 HOCS-5364 Use user from base image
  Dockerfile
Labels: patch

#1042 downgrade axios to 0.26.1 to resolve broken deployment
  package-lock.json
  package.json
Labels: patch

#1053 HOCS-5245: Add POGR search
  server/config/searchFields/config.json
Labels: minor
