Repository UKHomeOffice/hocs-frontend, pull requests merged in 2022-09, with the labels that each got.

#1110 HOCS-2239: Remove redundant certs container
  kube/kd/deployment.yaml
Labels: patch

#1109 HOCS-5560: rework unallocated accordion
  server/libs/__tests__/objectHelpers.spec.js
  server/libs/objectHelpers.js
  server/lists/adapters/__tests__/__snapshots__/case-view-all-stages.spec.js.snap
  server/lists/adapters/__tests__/case-view-all-stages.spec.js
  server/lists/adapters/case-view-all-stages.js
Labels: patch

#1113 HOCS-5503: Update complaint categories
  server/lists/index.js
Labels: minor

#1114 HOCS-5467 - Fix to display - user entered fields to the user in People tab
  src/shared/common/components/__tests__/people.spec.jsx
  src/shared/common/components/people.jsx
Labels: minor

#1117 HOCS-5498: Update IEDET complaint type screen
  src/shared/common/forms/radio-group.jsx
Labels: minor

#1115 HOCS-4815: Add IEDET assign screen
  server/lists/index.js
Labels: minor

#1124 HOCS-5498: IEDET Complaint type screen changes
  src/shared/common/forms/checkbox-grid.jsx
  src/shared/common/forms/checkbox-group.jsx
  src/shared/common/forms/radio-group.jsx
Labels: minor

#1125 HOCS-5629: Fix IEDET final response upload
  server/lists/index.js
Labels: minor

#1111 HOCS-4974 Update GOVUK Frontend to 4.3.1
  index.js
  package-lock.json
  package.json
  server/layout/__tests__/__snapshots__/html.spec.js.snap
  server/layout/html.js
  src/browser/index.js
  src/shared/common/components/__tests__/__snapshots__/side-bar.spec.jsx.snap
  src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap
  src/shared/common/components/case-note.jsx
  src/shared/common/components/case-notes.jsx
  src/shared/common/components/side-bar.jsx
  src/shared/common/components/workstack.jsx
  src/shared/common/forms/__tests__/__snapshots__/expandable-checkbox.spec.js.snap
  src/shared/common/forms/__tests__/__snapshots__/mapped-text.spec.js.snap
  src/shared/common/forms/__tests__/accordion.spec.js
  src/shared/common/forms/__tests__/date.spec.js
  src/shared/common/forms/accordion.jsx
  src/shared/common/forms/checkbox-grid.jsx
  src/shared/common/forms/checkbox-group.jsx
  src/shared/common/forms/composite/document-add.jsx
  src/shared/common/forms/composite/entity-list.jsx
  src/shared/common/forms/composite/somu-list.jsx
  src/shared/common/forms/date.jsx
  src/shared/common/forms/dropdown.jsx
  src/shared/common/forms/expandable-checkbox.jsx
  src/shared/common/forms/mapped-text.jsx
  src/shared/common/forms/radio-group.jsx
  src/shared/common/forms/text-area.jsx
  src/shared/common/forms/text.jsx
  src/shared/common/forms/type-ahead.jsx
  src/shared/layouts/components/__tests__/__snapshots__/footer.spec.js.snap
  src/shared/layouts/components/footer.jsx
  src/shared/layouts/components/header.jsx
  src/shared/pages/standardLines/standardLinesView.jsx
  src/styles/app.scss
Labels: patch, smoketest
