Repository UKHomeOffice/hocs-frontend, pull requests merged in 2022-03, with the labels that each got.

#899 HOCS-4696: use GitHub SemVer actions
  .drone.yml
  .github/workflows/label-check.yml
  .github/workflows/semver.yml
Labels: major

#902 Hocs-4696: replace deploy by SHA with TAG
  .drone.yml
Labels: patch

#900 HOCS-4749: simplify k8 linter/dry-run
  .drone.yml
  kube/.drone.yml
  kube/deploy.sh
Labels: patch

#903 HOCS-4760: fix lists for BF complaint reason
  server/lists/index.js
Labels: patch

#908 HOCS-4696: Override Dependabot labels
  .github/dependabot.yml
Labels: patch

#910 HOCS-4631 Add Interim Letters document list
  server/lists/index.js
Labels: minor

#907 HOCS-4696: Remove duplicate Sonar Run.
  .drone.yml
Labels: patch

#911 HOCS-4632 Add GRO Drafting Teams list
  server/lists/index.js
Labels: minor

#912 HOCS-4775: rename document list
  server/lists/index.js
Labels: patch

#913 HOCS-4774: pass through labels to document
  server/lists/adapters/__tests__/__snapshots__/documents.spec.js.snap
  server/lists/adapters/__tests__/documents.spec.js
  server/lists/adapters/documents.js
Labels: patch

#914 HOCS-4255: add exgratia tab to BF2
  src/shared/helpers/case-type-sidebar-tabs-flags.js
Labels: minor

#915 HOCS-4398 BF2 add interest to action tab
  server/lists/index.js
  src/shared/helpers/case-type-sidebar-tabs-flags.js
Labels: minor

#916 HOCS-4808: support tagging on support branches
  .drone.yml
Labels: patch

#909 HOCS-3736: create new teams and unit dropdown for foi
  server/lists/index.js
  src/shared/common/forms/__tests__/confirmation-with-team-name-and-case-ref.spec.js
  src/shared/common/forms/confirmation-with-team-name-and-case-ref.jsx
Labels: minor

#920 HOCS-4837 Add matrix to test against latest-LTS of NodeJS as well as prod version
  .drone.yml
Labels: skip-release

#922 HOCS-4634: add POGR contributions support
  server/services/forms/index.js
  src/shared/common/forms/composite/somu-list.jsx
Labels: minor
