Repository UKHomeOffice/hocs-frontend, pull requests merged in 2022-04, with the labels that each got.

#924 HOCS-4636: add Draft document list to index
  server/lists/index.js
Labels: minor

#926 HOCS-4779: Add currency validation to ex-gratia tab BF
  server/middleware/__tests__/validation.spec.js
  server/middleware/validation.js
  server/routes/api/case.js
  server/services/schema.js
  src/shared/common/components/tab-ex-gratia.jsx
  src/shared/common/forms/form-embedded-wrapped.jsx
Labels: minor

#928 HOCS-4862: update match label action version
  .github/workflows/pr-check.yml
  .github/workflows/semver.yml
Labels: skip-release

#929 HOCS-4921: trim case note contents
  server/middleware/__tests__/case.spec.js
  server/middleware/case.js
Labels: patch

#931 HOCS-4941: introduce strict currency validation
  server/middleware/__tests__/validation.spec.js
  server/middleware/validation.js
Labels: minor

#937 HOCS-4954: bump UUID to latest
  package-lock.json
  package.json
  server/middleware/file.js
  server/middleware/request.js
  server/services/forms/schemas/extend-deadline.js
  server/services/forms/schemas/manage-people.js
  server/tenantConfig.js
Labels: patch

#936 Upgrade to latest Webpack 5.x
  package-lock.json
  package.json
  webpack.config.js
Labels: minor

#955 Remove homeoffice Quay proxy
  kube/kd/deployment.yaml
Labels: patch

#932 HOCS-3803: smc suspend feature
  server/libs/__tests__/deadlineDisplayHelpers.spec.js
  server/libs/deadlineDisplayHelpers.js
  server/lists/adapters/__tests__/__snapshots__/case-summary.spec.js.snap
  server/lists/adapters/__tests__/workstacks.spec.js
  server/lists/adapters/actions/__tests__/extensionsSummaryAdapter.spec.js
  server/lists/adapters/actions/actionsSummaryAdapterFactory.js
  server/lists/adapters/actions/extensionsSummaryAdapter.js
  server/lists/adapters/case-notes.js
  server/lists/adapters/case-summary.js
  server/lists/adapters/workstacks.js
  server/services/action.js
  server/services/actions/types.js
  server/services/forms/index.js
  server/services/forms/schemas/__tests__/index.spec.js
  server/services/forms/schemas/index.js
  server/services/forms/schemas/record-appeal.js
  server/services/forms/schemas/record-interest.js
  server/services/forms/schemas/remove-suspension.js
  server/services/forms/schemas/suspend-case.js
  server/services/forms/schemas/update-appeal.js
  src/shared/common/components/__tests__/__snapshots__/side-bar.spec.jsx.snap
  src/shared/common/components/__tests__/__snapshots__/suspensions.spec.jsx.snap
  src/shared/common/components/__tests__/suspensions.spec.jsx
  src/shared/common/components/case-action-factory.jsx
  src/shared/common/components/case-actions.jsx
  src/shared/common/components/side-bar.jsx
  src/shared/common/components/suspensions.jsx
  src/shared/common/components/workstack.jsx
  src/shared/helpers/api-status.js
  src/shared/helpers/case-type-sidebar-tabs-flags.js
  src/shared/pages/case.jsx
Labels: minor

#958 HOCS-4826 Replace npm install with npm ci
  .drone.yml
  Dockerfile
Labels: patch
