Repository UKHomeOffice/hocs-frontend, pull requests merged in 2022-08, with the labels that each got.

#1059 HOCS-4270: fix falsey casenote request
  server/middleware/__tests__/case.spec.js
  server/middleware/case.js
Labels: patch

#1057 HOCS-4791: Add ability to create POGR2 cases
  server/services/forms/index.js
Labels: minor

#1063 HOCS-5412: remove POGR search field
  server/config/searchFields/config.json
Labels: patch

#1064 HOCS-4781: Add POGR complaint entities
  server/lists/index.js
Labels: minor

#1068 HOCS-5457: fix visible fields validation
  server/middleware/form/__tests__/process.spec.js
  server/middleware/form/__tests__/validation.spec.js
  server/middleware/form/process.js
  server/middleware/form/validation.js
Labels: patch

#1069 HOCS-5363: form embedded cleanup
  src/shared/common/components/tab-ex-gratia.jsx
  src/shared/common/forms/form-embedded-wrapped.jsx
Labels: minor

#1070 HOCS-5363: add POGR Ex-Gratia tab configuration
  server/config/caseTabs/config.json
Labels: minor

#1071 HOCS-4782: add GRO ex-gratia entity list
  server/lists/index.js
Labels: minor

#1073 HOCS-2646 Point feedback link to new email address
  server/tenantConfig.js
Labels: patch

#1074 HOCS-1504 Updated labels on correspondent forms
  server/services/forms/schemas/add-correspondent-details.js
  server/services/forms/schemas/add-member-details.js
  server/services/forms/schemas/decorators/__test__/form-decorations.spec.js
  server/services/forms/schemas/decorators/form_decorations/schema-decorations.js
  server/services/forms/schemas/update-correspondent-details-foi.js
  server/services/forms/schemas/update-correspondent-details.js
Labels: patch

#1076 HOCS-5475: Add WCS tabs to frontend config
  server/config/caseTabs/config.json
Labels: patch

#1080 Update multer and nodemon dependancies
  package-lock.json
  package.json
Labels: patch

#1081 Update Jest to 26.x
  package-lock.json
  package.json
Labels: patch

#1078 HOCS-5361: add static lists
  server/lists/index.js
Labels: minor

#1077 HOCS-5338: add POGR stage 2 search fields
  server/config/searchFields/config.json
Labels: patch

#1090 Remove nodecron dependancy and usage
  kube/kd/deployment.yaml
  package-lock.json
  package.json
  server/config.js
  server/services/list/__tests__/scheduler.spec.js
  server/services/list/scheduler.js
  server/services/list/service.js
Labels: minor

#1083 Remove contribution forms
  server/services/forms/schemas/__tests__/index.spec.js
  server/services/forms/schemas/contribution-fulfillment-foi.js
  server/services/forms/schemas/contribution-fulfillment.js
  server/services/forms/schemas/contribution-request-foi.js
  server/services/forms/schemas/contribution-request.js
  server/services/forms/schemas/index.js
Labels: patch

#1082 [HOCS-4838] Run on Node 16.x
  .eslintrc.js
  .github/workflows/test.yml
  Dockerfile
  README.md
  package-lock.json
  package.json
  server/middleware/__tests__/workstack.spec.js
  src/shared/common/components/appeals.jsx
  src/shared/common/components/case-notes.jsx
  src/shared/common/components/dashboard.jsx
  src/shared/common/components/extensions.jsx
  src/shared/common/components/external-interest.jsx
  src/shared/common/components/summary/actions/action-summary-appeals.jsx
  src/shared/common/forms/form.new.jsx
  src/shared/layouts/notifaction.jsx
  src/shared/pages/dashboard.jsx
  src/shared/pages/form-enabled.jsx
  src/shared/pages/search.jsx
Labels: major, smoketest

#1094 HOCS-5453: add new static list
  server/lists/index.js
Labels: minor

#1093 HOCS-5483: Remove escalation document requirement
  server/services/forms/index.js
  server/services/forms/schemas/document-add-next-case.js
Labels: minor

#1095 HOCS-5454: add new lists
  server/lists/index.js
Labels: minor

#1096 HOCS-5455: add static lists
  server/lists/index.js
Labels: minor

#1097 HOCS-5477: Update POGR business areas
  server/lists/index.js
Labels: minor

#1099 HOCS 5360 add TO BF enquiry lists
  server/lists/index.js
Labels: minor

#1100 Alter maxUnavailable to 0 based on prod experience
  kube/kd/deployment.yaml
Labels: patch

#1104 HOCS-4794 Update GOVUK Frontend to 4.3.1
  package-lock.json
  package.json
  server/layout/__tests__/__snapshots__/html.spec.js.snap
  server/layout/html.js
  src/browser/index.js
  src/shared/common/components/__tests__/__snapshots__/side-bar.spec.jsx.snap
  src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap
  src/shared/common/components/case-note.jsx
  src/shared/common/components/case-notes.jsx
  src/shared/common/components/side-bar.jsx
  src/shared/common/components/workstack.jsx
  src/shared/common/forms/__tests__/__snapshots__/expandable-checkbox.spec.js.snap
  src/shared/common/forms/__tests__/__snapshots__/mapped-text.spec.js.snap
  src/shared/common/forms/__tests__/accordion.spec.js
  src/shared/common/forms/__tests__/date.spec.js
  src/shared/common/forms/accordion.jsx
  src/shared/common/forms/checkbox-grid.jsx
  src/shared/common/forms/checkbox-group.jsx
  src/shared/common/forms/composite/document-add.jsx
  src/shared/common/forms/composite/entity-list.jsx
  src/shared/common/forms/composite/somu-list.jsx
  src/shared/common/forms/date.jsx
  src/shared/common/forms/dropdown.jsx
  src/shared/common/forms/expandable-checkbox.jsx
  src/shared/common/forms/mapped-text.jsx
  src/shared/common/forms/radio-group.jsx
  src/shared/common/forms/text-area.jsx
  src/shared/common/forms/text.jsx
  src/shared/common/forms/type-ahead.jsx
  src/shared/layouts/components/__tests__/__snapshots__/footer.spec.js.snap
  src/shared/layouts/components/footer.jsx
  src/shared/layouts/components/header.jsx
  src/shared/pages/standardLines/standardLinesView.jsx
  src/styles/app.scss
Labels: patch
