Repository UKHomeOffice/hocs-frontend, pull requests merged in 2022-12, with the labels that each got.

#1210 HOCS-5581: Set allocate margin to zero
  src/shared/common/components/workstack.jsx
Labels: patch

#1208 [HOCS-5349] Update to React 18 and Node 18
  .github/workflows/docker-build-branch.yml
  .github/workflows/docker-build-tag.yml
  Dockerfile
  package-lock.json
  package.json
  src/browser/index.js
  src/shared/common/forms/__tests__/__snapshots__/confirmation-with-team-name-and-case-ref.spec.js.snap
  src/shared/common/forms/__tests__/__snapshots__/expandable-checkbox.spec.js.snap
Labels: dependencies, patch, smoketest

#1205 HOCS-5566-Add tag row to show Rejected by PSU tag
  server/config/tagType/__tests__/tagType.spec.js
  server/config/tagType/tagConfig.json
  server/config/tagType/tagType.js
  src/shared/common/components/__tests__/workstack-tag.spec.jsx
  src/shared/common/components/workstack-tag.jsx
  src/shared/common/components/workstack.jsx
Labels: minor

#1216 HOCS-5979: Add IEDET category validation
  server/middleware/form/__tests__/process.spec.js
  server/middleware/form/__tests__/validation.spec.js
  server/middleware/form/process.js
  server/middleware/form/validation.js
Labels: minor

#1209 HOCS-5564: Implement business events
  server/lists/adapters/__tests__/__snapshots__/case-notes.spec.js.snap
  server/lists/adapters/__tests__/case-notes.spec.js
  server/lists/adapters/case-notes.js
  server/middleware/case-notes.js
Labels: minor

#1218 HOCS-2298: Load case error messages for non-real reference is poorly worded
  server/routes/dashboard.js
Labels: minor

#1220 Chore: Update test matrix to node 18.x, 19.x
  .github/workflows/test.yml
Labels: patch
