Repository UKHomeOffice/hocs-frontend, pull requests merged in 2023-11, with the labels that each got.

#1447 HOCS-2918: Fix textbox whitespace char count issues
  src/shared/common/forms/text-area.jsx
Labels: minor

#1452 HOCS-6844: Bump axios to version 1.6.2
  package-lock.json
  package.json
Labels: minor

#1449 HOCS-4651: Fix redundant label
  src/shared/common/forms/composite/somu-list.jsx
Labels: patch

#1451 HOCS-4650: Remove layout table
  src/shared/common/forms/composite/entity-list.jsx
Labels: minor

#1454 Fix/hocs 4640 replace layout table
  src/shared/common/components/__tests__/__snapshots__/appeals.spec.jsx.snap
  src/shared/common/components/__tests__/__snapshots__/external-interest.spec.jsx.snap
  src/shared/common/components/appeals.jsx
  src/shared/common/components/external-interest.jsx
Labels: patch

#1455 HOCS-4641: Remove layout table
  src/shared/common/forms/__tests__/__snapshots__/form-embedded-wrapped.spec.js.snap
  src/shared/common/forms/summary.jsx
Labels: patch

#1456 HOCS-4649: Remove layout table
  src/shared/common/forms/composite/somu-list.jsx
Labels: patch

#1457 HOCS-2079: Associate label in workstacks
  src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap
  src/shared/common/components/workstack.jsx
Labels: patch

#1458 HOCS-6820:Update keycloak 22 realm url in frontend
  helm/hocs-frontend-wcs.yaml
  helm/hocs-frontend.yaml
Labels: minor, smoketest

#1461 HOCS-2081: Fix double labels on document add component
  src/shared/common/forms/composite/document-add.jsx
Labels: patch
