Repository UKHomeOffice/hocs-frontend, pull requests merged in 2023-04, with the labels that each got.

#1265 [HOCS-6267] Front end routes for operational reports
  .babelrc
  .eslintrc.js
  package-lock.json
  package.json
  server/lists/adapters/report.js
  server/lists/index.js
  server/middleware/report.js
  server/routes/api/index.js
  server/routes/api/report.js
  src/shared/reports/__tests__/buildCompletablePromise.spec.utils.ts
  src/shared/reports/__tests__/reportListView.spec.tsx
  src/shared/reports/__tests__/reportView.spec.tsx
  src/shared/reports/components/charts.tsx
  src/shared/reports/components/dataTable.tsx
  src/shared/reports/components/filterForm.tsx
  src/shared/reports/components/filters/boolean.tsx
  src/shared/reports/components/filters/dateRange.tsx
  src/shared/reports/components/filters/fieldset.tsx
  src/shared/reports/components/filters/formGroup.tsx
  src/shared/reports/components/filters/select.tsx
  src/shared/reports/components/filters/text.tsx
  src/shared/reports/components/pagination.tsx
  src/shared/reports/reportListView.tsx
  src/shared/reports/reportView.tsx
  src/shared/router/routes/index.js
  src/styles/app.scss
  tsconfig.json
  webpack.config.js
Labels: minor

#1270 HOCS-6501: change PsuReference in search data blob
  server/middleware/searchHandler.js
Labels: patch

#1271 [HOCS-6510] Remove operational reporting list until infrastructure is in place
  server/lists/index.js
  src/shared/reports/components/dataTable.tsx
Labels: patch

#1279 HOCS-6513: support new static list
  server/lists/index.js
Labels: minor

#1280 HOCS-6261: support hint text in somu-list
  src/shared/common/forms/composite/__tests__/somu-list.spec.jsx
  src/shared/common/forms/composite/somu-list.jsx
Labels: minor

#1284 HOCS-4913: Update mapped display to use divs
  src/shared/common/forms/__tests__/__snapshots__/mapped-display.spec.js.snap
  src/shared/common/forms/mapped-display.jsx
Labels: patch

#1291 Update vulnerable YAML package
  package-lock.json
Labels: dependencies, patch

#1286 HOCS-4963: Remove unused min/max attributes from date
  src/shared/common/forms/__tests__/date.spec.js
  src/shared/common/forms/date.jsx
Labels: patch

#1292 Ignore AWS-SDK dependency updates
  .github/dependabot.yml
Labels: skip-release

#1296 Improve correlation ID use
  server/lists/adapters/case-summary.js
  server/middleware/__tests__/document.spec.js
  server/middleware/__tests__/searchHandler.spec.js
  server/middleware/__tests__/standardLines.spec.js
  server/middleware/__tests__/workstack.spec.js
  server/middleware/action.js
  server/middleware/case.js
  server/middleware/document.js
  server/middleware/report.js
  server/middleware/searchHandler.js
  server/middleware/somu.js
  server/middleware/stage.js
  server/middleware/standardLine.js
  server/middleware/templates.js
  server/middleware/workstack.js
  server/routes/dashboard.js
  server/services/action.js
  server/services/forms/schemas/remove-correspondent.js
  server/services/forms/schemas/remove-document.js
  server/services/forms/schemas/remove-topic.js
  server/services/forms/schemas/search.js
  server/services/forms/schemas/update-correspondent-details-foi.js
  server/services/forms/schemas/update-correspondent-details.js
  server/services/list/service.js
Labels: patch

#1297 Add return to all `next` calls
  server/middleware/__tests__/autoCreateAllocate.spec.js
  server/middleware/action.js
  server/middleware/auth.js
  server/middleware/cacheControl.js
  server/middleware/case-notes.js
  server/middleware/case.js
  server/middleware/dashboard.js
  server/middleware/document.js
  server/middleware/form/process.js
  server/middleware/render.js
  server/middleware/report.js
  server/middleware/request.js
  server/middleware/searchHandler.js
  server/middleware/somu.js
  server/middleware/standardLine.js
  server/middleware/templates.js
  server/middleware/workstack.js
  server/routes/api/workstack.js
  server/routes/dashboard.js
  server/routes/index.js
  server/routes/page.js
  server/routes/search.js
  server/services/form.js
Labels: patch

#1294 HOCS-4931: improve skip link
  src/shared/layouts/components/__tests__/__snapshots__/body.spec.js.snap
  src/shared/layouts/components/__tests__/skip-link.spec.js
  src/shared/layouts/components/body.jsx
  src/shared/layouts/components/header.jsx
  src/shared/layouts/components/skip-link.jsx
Labels: patch, smoketest

#1298 Make form events specific
  server/middleware/stage.js
  server/services/form.js
Labels: patch

#1299 Pass-through request id to functions
  server/services/form.js
  server/services/list/service.js
Labels: patch

#1300 Pass-through request id to function
  server/routes/search.js
Labels: patch
