Repository UKHomeOffice/hocs-frontend, pull requests merged in 2023-06, with the labels that each got.

#1343 HOCS-6562: change document handling
  server/middleware/__tests__/document.spec.js
  server/middleware/document.js
  server/routes/document.js
Labels: minor

#1350 Run NPM Audit
  package-lock.json
Labels: dependencies, patch

#1348 HOCS-6656: improve date handling
  server/middleware/form/__tests__/process.spec.js
  server/middleware/form/process.js
Labels: minor

#1354 Update minimum helm chart version
  .drone.yml
Labels: patch
